apiVersion: apps/v1
kind: Deployment
metadata:
  name: uipath-robots
  labels:
    app: uipath-robots
  namespace: robot-workers
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  replicas: 4
  selector:
    matchLabels:
      app: uipath-robots
  template:
    metadata:
      labels:
        app: uipath-robots
    spec:
      containers:
        - image: registry.uipath.com/robot/runtime:22.10.3
          name: uipath-robot-container
          securityContext:
            privileged: false
          env:
            - name: MACHINE_KEY
              valueFrom:
                configMapKeyRef:
                  name: uipath-config
                  key: MACHINE_KEY
            - name: ORCHESTRATOR_URL
              valueFrom:
                configMapKeyRef:
                  name: uipath-config
                  key: ORCHESTRATOR_URL
            - name: LICENSE_AGREEMENT
              valueFrom:
                configMapKeyRef:
                  name: uipath-config
                  key: LICENSE_AGREEMENT
